#pragma once
void ws_setup();
void ws_loop();
void mt_setup();
void mt_loop();
void ffs_setup();
void ffs_loop();
void json_setup();
void strimg_setup();
void tester_list();
void tester_map();
void tester_str_list();
